version: '3.8'
services:
  laravel-training:
    container_name: laravel-training-app
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    volumes:
      - ./:/var/www
    extra_hosts:
      - "laravel_training.zend:127.0.0.1"
    hostname: laravel_training.zend
    domainname: local
    ports:
      - 8000:80
  db:
    container_name: laravel-training-db
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    ports:
      - 3307:3306
    volumes:
      - ./containers/db/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
